# Generated by Django 6.0.3 on 2026-03-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]

